apiVersion: v2
name: heartflow-demo
description: HeartFlow Demo Service for Spectro Cloud Edge Workshop
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: nctiggy
keywords:
  - heartflow
  - demo
  - edge
  - spectrocloud
