apiVersion: v2
name: heartflow-demo
description: HeartFlow Demo Service for Spectro Cloud Edge Workshop
type: application
version: 1.2.0
appVersion: "2.0.0"
maintainers:
  - name: nctiggy
keywords:
  - heartflow
  - demo
  - edge
  - spectrocloud
