{{- if .Values.gpuInference.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wwt-custom-app.fullname" . }}-gpu-inference
  labels:
    {{- include "wwt-custom-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: gpu-inference
spec:
  type: {{ .Values.gpuInference.service.type }}
  ports:
    - port: {{ .Values.gpuInference.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.gpuInference.service.type "NodePort") .Values.gpuInference.service.nodePort }}
      nodePort: {{ .Values.gpuInference.service.nodePort }}
      {{- end }}
  selector:
    {{- include "wwt-custom-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gpu-inference
{{- end }}
